Ramazanov
avalon-dev-j30/lab-2-ramazanovmax pull request #1
Opened 2019-06-01 13:20 UTC by ramazanovmax

2019-06-02 13:19 UTC, konivex requested changes
Исправьте замечания.

2019-06-02 13:19 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
> -        throw new UnsupportedOperationException("Not implemented yet!");
Ни в одном месте вашего класса нет кода, в котором бы присутствовали старый и новый код продукта одновременно, так что в части SET SQL-оператора UPDATE установка значения поля prod_code бессмысленна.

2019-06-05 22:04 UTC, ramazanovmax commented
Исправление замечаний

2019-06-05 22:04 UTC, merged

2019-06-06 15:13 UTC, konivex reviewed
Исправьте замечание.

2019-06-06 15:13 UTC, konivex commented on src/ru/avalon/java/j30/labs/ProductCode.java
>      public void save(Connection connection) throws SQLException {
Метод не будет работать при вставке записи.